<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3sixshop"
 *
 * Auto generated by Extension Builder 2013-05-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Shop for T3 v6+',
	'description' => 'Shop extension for TYPO3 6.x',
	'category' => 'plugin',
	'author' => 'Anisur Rahaman Mullick',
	'author_email' => 'anisur@armtechnologies.com',
	'author_company' => 'ARM Technologies',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.3',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>